# [font]
# normal = { family = "Fira Code", style = "Medium" }
# size = 12.5

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 13.0

[font.offset]
y = 3

[colors.primary]
background = "#000000"
foreground = "#ffffff"

# [colors.normal]
# black   = "#000000"
# red     = "#ff0000"
# green   = "#00ff00"
# yellow  = "#ffff00"
# blue    = "#0000ff"
# magenta = "#ff00ff"
# cyan    = "#00ffff"
# white   = "#ffffff"
#
# [colors.bright]
# black   = "#808080"
# red     = "#ff5555"
# green   = "#55ff55"
# yellow  = "#ffff55"
# blue    = "#5555ff"
# magenta = "#ff55ff"
# cyan    = "#55ffff"
# white   = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#cd3131"
green   = "#0dbc79"
yellow  = "#e5e510"
blue    = "#2472c8"
magenta = "#bc3fbc"
cyan    = "#11a8cd"
white   = "#e5e5e5"

[colors.bright]
black   = "#666666"
red     = "#f14c4c"
green   = "#23d18b"
yellow  = "#f5f543"
blue    = "#3b8eea"
magenta = "#d670d6"
cyan    = "#29b8db"
white   = "#e5e5e5"

[window]
decorations = "None"
dynamic_padding = false

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 200
lines = 50

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = false

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

[cursor.style]
blinking = "Never"
